name: Stock Price Predictor

on:
  schedule:
    - cron: '0 1 * * 1'  # Runs at 01:00 UTC every Monday
  workflow_dispatch:  # Allows manual triggering

jobs:
  predict_stocks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run prediction script
      run: python stock_predictor.py
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add prediction_results.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update stock predictions" && git push)